"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#2nen21%j#(5j@=@e-t!ep!z*p70w36ni%e$he0a4$$)b+)7o&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.OperatorRedirectMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Media files (yuklangan chek/skrinshotlar)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# amoCRM integratsiyasi (API v4, uzoq muddatli token).
# Kalitlarni muhit o'zgaruvchilari orqali bering (masalan .env yoki eksport).
#   AMOCRM_SUBDOMAIN — masalan `mycompany` (mycompany.amocrm.ru uchun)
#   AMOCRM_TOKEN     — amoCRM → Sozlamalar → Integratsiyalar dan olingan token
AMOCRM = {
    "SUBDOMAIN": os.environ.get("AMOCRM_SUBDOMAIN", ""),
    "TOKEN": os.environ.get("AMOCRM_TOKEN", ""),
}

# Telegram bot integratsiyasi.
# To'lov tasdiqlanganda bitta umumiy Telegram guruh chatiga QR kod yuboriladi.
# BotFather bergan tokenni TELEGRAM_BOT_TOKEN, guruh chat ID sini esa
# TELEGRAM_CHAT_ID muhit o'zgaruvchisiga bering (masalan -1001234567890).
TELEGRAM = {
    "BOT_TOKEN": os.environ.get("TELEGRAM_BOT_TOKEN", ""),
    "CHAT_ID": os.environ.get("TELEGRAM_CHAT_ID", ""),
}


# Sidebar'da "To'lovlar", "Tasdiqlanmagan to'lovlar" va "Qaytarilgan to'lovlar"
# bir xil URL yo'liga ega, shuning uchun active holatini query parametr bo'yicha ajratamiz.
def _in_transaction_changelist(request):
    return request.path.startswith("/admin/main/transaction/") and "add" not in request.path


def _is_refunded_transactions_view(request):
    return _in_transaction_changelist(request) and request.GET.get("is_refunded__exact") == "1"


def _is_unconfirmed_transactions_view(request):
    return _in_transaction_changelist(request) and request.GET.get("is_confirmed__exact") == "0"


def _is_payments_view(request):
    return (
        _in_transaction_changelist(request)
        and request.GET.get("is_refunded__exact") != "1"
        and request.GET.get("is_confirmed__exact") != "0"
    )


UNFOLD = {
    "SITE_TITLE": "Norbekov Markazi",
    "SITE_HEADER": "Norbekov Markazi",
    "SITE_URL": "/",
    "SITE_SYMBOL": "medication",
    "DASHBOARD_CALLBACK": "main.views.dashboard_callback",
    # DIQQAT: unfold 0.67 bu qiymatlarni to'g'ridan-to'g'ri `var(--color-primary-600)`
    # ichiga qo'yadi va CSS rangi sifatida ishlatadi. Shuning uchun ular haqiqiy CSS
    # rangi bo'lishi shart — "82 82 82" ko'rinishidagi RGB triplet brauzer tomonidan
    # e'tiborsiz qoldiriladi va butun interfeys kulrangga aylanib qoladi.
    "COLORS": {
        # Dorixona/tibbiyotga mos to'q ko'k-yashil (teal) palitra. 600 qiymati
        # oq matn bilan WCAG AA dan o'tadigan darajada to'q tanlangan.
        "primary": {
            "50": "#f0fdfa",
            "100": "#d9f7f0",
            "200": "#a7ece0",
            "300": "#6ddac9",
            "400": "#34c1ad",
            "500": "#14a394",
            "600": "#0f766e",
            "700": "#115e59",
            "800": "#134e4a",
            "900": "#10403d",
            "950": "#062e2c",
        },
        # Neytral kulrang ohangga bir oz iliqlik/ko'klik qo'shiladi — sof qora-oq
        # o'rniga yumshoqroq fon beradi.
        "base": {
            "50": "#f7f9f9",
            "100": "#eef2f2",
            "200": "#dfe6e6",
            "300": "#c5d0d1",
            "400": "#94a4a5",
            "500": "#697a7b",
            "600": "#4e5f60",
            "700": "#3c4b4c",
            "800": "#25302f",
            "900": "#161e1e",
            "950": "#0b1111",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Ish stoli",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                        "permission": "main.permissions.is_not_plain_operator",
                    },
                    {
                        "title": "Maosh hisob-kitobi",
                        "icon": "payments",
                        "link": "/salaries/",
                    },
                    {
                        "title": "QR skaner",
                        "icon": "qr_code_scanner",
                        "link": "/qr-verify/",
                    },
                ],
            },
            {
                "title": "Ma'lumotlar",
                "separator": True,
                "items": [
                    {
                        "title": "Kurslar",
                        "icon": "school",
                        "link": "/admin/main/course/",
                    },
                    {
                        "title": "Guruhlar",
                        "icon": "groups",
                        "link": "/admin/main/group/",
                    },
                    {
                        "title": "Mijozlar",
                        "icon": "people",
                        "link": "/admin/main/client/",
                    },
                    {
                        "title": "Operatorlar",
                        "icon": "support_agent",
                        "link": "/admin/main/operator/",
                        "permission": "main.permissions.is_not_plain_operator",
                    },
                    {
                        "title": "Chegirmalar",
                        "icon": "sell",
                        "link": "/admin/main/discount/",
                    },
                ],
            },
            {
                "title": "Moliya",
                "separator": True,
                "items": [
                    {
                        "title": "To'lovlar",
                        "icon": "payments",
                        "link": "/admin/main/transaction/",
                        "active": _is_payments_view,
                    },
                    {
                        "title": "Tasdiqlash navbati",
                        "icon": "pending_actions",
                        "link": "/admin/main/transaction/?is_confirmed__exact=0",
                        "active": _is_unconfirmed_transactions_view,
                    },
                    {
                        "title": "Ichki to'lovlar",
                        "icon": "receipt_long",
                        "link": "/admin/main/subtransaction/?status__exact=pending",
                    },
                    {
                        "title": "Qaytarilganlar",
                        "icon": "assignment_return",
                        "link": "/admin/main/transaction/?is_refunded__exact=1",
                        "active": _is_refunded_transactions_view,
                    },
                ],
            },
        ],
    },
}
