"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#2nen21%j#(5j@=@e-t!ep!z*p70w36ni%e$he0a4$$)b+)7o&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.OperatorRedirectMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Media files (yuklangan chek/skrinshotlar)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# amoCRM integratsiyasi (amocrm-api kutubxonasi orqali).
# Kalitlarni muhit o'zgaruvchilari orqali bering (masalan .env yoki eksport).
AMOCRM = {
    "CLIENT_ID": os.environ.get("AMOCRM_CLIENT_ID", ""),
    "CLIENT_SECRET": os.environ.get("AMOCRM_CLIENT_SECRET", ""),
    "SUBDOMAIN": os.environ.get("AMOCRM_SUBDOMAIN", ""),
    "REDIRECT_URL": os.environ.get("AMOCRM_REDIRECT_URL", ""),
    # OAuth authorization code — birinchi ulanishda kerak bo'ladi.
    "AUTH_CODE": os.environ.get("AMOCRM_AUTH_CODE", ""),
    # Tokenlar shu faylda saqlanadi.
    "TOKENS_PATH": str(BASE_DIR / ".amocrm_tokens.json"),
}


# Sidebar'da "To'lovlar", "Tasdiqlanmagan to'lovlar" va "Qaytarilgan to'lovlar"
# bir xil URL yo'liga ega, shuning uchun active holatini query parametr bo'yicha ajratamiz.
def _in_transaction_changelist(request):
    return request.path.startswith("/admin/main/transaction/") and "add" not in request.path


def _is_refunded_transactions_view(request):
    return _in_transaction_changelist(request) and request.GET.get("is_refunded__exact") == "1"


def _is_unconfirmed_transactions_view(request):
    return _in_transaction_changelist(request) and request.GET.get("is_confirmed__exact") == "0"


def _is_payments_view(request):
    return (
        _in_transaction_changelist(request)
        and request.GET.get("is_refunded__exact") != "1"
        and request.GET.get("is_confirmed__exact") != "0"
    )


UNFOLD = {
    "SITE_TITLE": "Norbekov Markazi",
    "SITE_HEADER": "Norbekov Markazi",
    "SITE_URL": "/",
    "SITE_SYMBOL": "science",
    "DASHBOARD_CALLBACK": "main.views.dashboard_callback",
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Asosiy",
                "separator": True,
                "items": [
                    {
                        "title": "Bosh sahifa",
                        "icon": "dashboard",
                        "link": "/admin/",
                        "permission": "main.permissions.is_not_plain_operator",
                    },
                    {
                        "title": "Maoshlar",
                        "icon": "payments",
                        "link": "/salaries/",
                    },
                ],
            },
            {
                "title": "Ma'lumotlar bazasi",
                "separator": True,
                "items": [
                    {
                        "title": "Kurslar",
                        "icon": "school",
                        "link": "/admin/main/course/",
                    },
                    {
                        "title": "Guruhlar",
                        "icon": "groups",
                        "link": "/admin/main/group/",
                    },
                    {
                        "title": "Mijozlar",
                        "icon": "people",
                        "link": "/admin/main/client/",
                    },
                    {
                        "title": "Operatorlar",
                        "icon": "support_agent",
                        "link": "/admin/main/operator/",
                        "permission": "main.permissions.is_not_plain_operator",
                    },
                    {
                        "title": "Chegirmalar",
                        "icon": "sell",
                        "link": "/admin/main/discount/",
                    },
                ],
            },
            {
                "title": "To'lovlar",
                "separator": True,
                "items": [
                    {
                        "title": "To'lovlar",
                        "icon": "payments",
                        "link": "/admin/main/transaction/",
                        "active": _is_payments_view,
                    },
                    {
                        "title": "Tasdiqlanmagan to'lovlar",
                        "icon": "pending_actions",
                        "link": "/admin/main/transaction/?is_confirmed__exact=0",
                        "active": _is_unconfirmed_transactions_view,
                    },
                    {
                        "title": "Qaytarilgan to'lovlar",
                        "icon": "assignment_return",
                        "link": "/admin/main/transaction/?is_refunded__exact=1",
                        "active": _is_refunded_transactions_view,
                    },
                ],
            },
        ],
    },
}
