"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env(path):
    """Load the project's ignored .env file without overriding deployed env vars."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if value[:1] == value[-1:] and value[:1] in {"'", '"'}:
            value = value[1:-1]
        os.environ.setdefault(key, value)


_load_local_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-#2nen21%j#(5j@=@e-t!ep!z*p70w36ni%e$he0a4$$)b+)7o&',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').strip().lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Production Nginx HTTPS ni tugatadi va X-Forwarded-Proto sarlavhasini uzatadi.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middleware.OperatorRedirectMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'main.backends.RolePermissionBackend',
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Media files (yuklangan chek/skrinshotlar)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# amoCRM integratsiyasi (API v4, uzoq muddatli token).
# Kalitlarni muhit o'zgaruvchilari orqali bering (masalan .env yoki eksport).
#   AMOCRM_SUBDOMAIN — masalan `mycompany` (mycompany.amocrm.ru uchun)
#   AMOCRM_TOKEN     — amoCRM → Sozlamalar → Integratsiyalar dan olingan token
AMOCRM = {
    "SUBDOMAIN": os.environ.get("AMOCRM_SUBDOMAIN", ""),
    "TOKEN": os.environ.get("AMOCRM_TOKEN", ""),
}

# Telegram bot integratsiyasi.
# To'lov tasdiqlanganda bitta umumiy Telegram guruh chatiga QR kod yuboriladi.
# BotFather bergan tokenni TELEGRAM_BOT_TOKEN, guruh chat ID sini esa
# TELEGRAM_CHAT_ID muhit o'zgaruvchisiga bering (masalan -1001234567890).
TELEGRAM = {
    "BOT_TOKEN": os.environ.get("TELEGRAM_BOT_TOKEN", ""),
    "CHAT_ID": os.environ.get("TELEGRAM_CHAT_ID", ""),
    "WEB_APP_URL": os.environ.get("TELEGRAM_WEB_APP_URL", ""),
    "WEBHOOK_SECRET": os.environ.get("TELEGRAM_WEBHOOK_SECRET", ""),
    "PREFER_IPV6": os.environ.get("TELEGRAM_PREFER_IPV6", "").lower() in {"1", "true", "yes"},
}

# Multicard hosted checkout. Keep disabled until merchant configuration is complete.
MULTICARD = {
    'ENABLED': os.environ.get('MULTICARD_ENABLED', '').lower() in {'1', 'true', 'yes'},
    'BASE_URL': os.environ.get('MULTICARD_BASE_URL', 'https://dev-mesh.multicard.uz'),
    'APPLICATION_ID': os.environ.get('MULTICARD_APPLICATION_ID', ''),
    'SECRET': os.environ.get('MULTICARD_SECRET', ''),
    'STORE_ID': os.environ.get('MULTICARD_STORE_ID', ''),
    'CALLBACK_URL': os.environ.get(
        'MULTICARD_CALLBACK_URL',
        'https://crm.norbekovmarkazi.uz/payments/multicard/callback/',
    ),
    'RETURN_URL': os.environ.get('MULTICARD_RETURN_URL', ''),
    'OFD_MXIK': os.environ.get('MULTICARD_OFD_MXIK', ''),
    'OFD_PACKAGE_CODE': os.environ.get('MULTICARD_OFD_PACKAGE_CODE', ''),
    'OFD_VAT': os.environ.get('MULTICARD_OFD_VAT', ''),
}


# Sidebar'da "To'lovlar", "Tasdiqlanmagan to'lovlar" va "Qaytarilgan to'lovlar"
# bir xil URL yo'liga ega, shuning uchun active holatini query parametr bo'yicha ajratamiz.
def _in_transaction_changelist(request):
    return request.path.startswith("/admin/main/transaction/") and "add" not in request.path


def _is_refunded_transactions_view(request):
    return _in_transaction_changelist(request) and request.GET.get("is_refunded__exact") == "1"


def _is_unconfirmed_transactions_view(request):
    return _in_transaction_changelist(request) and request.GET.get("is_confirmed__exact") == "0"


def _is_payments_view(request):
    return (
        _in_transaction_changelist(request)
        and request.GET.get("is_refunded__exact") != "1"
        and request.GET.get("is_confirmed__exact") != "0"
    )


UNFOLD = {
    "SITE_TITLE": "Norbekov Markazi",
    "SITE_HEADER": "Norbekov Markazi",
    "SITE_URL": "/",
    "SITE_LOGO": {
        "light": "/static/main/brand/norbekov-logo-light.svg",
        "dark": "/static/main/brand/norbekov-logo-dark.svg",
    },
    "SITE_ICON": {
        "light": "/static/main/brand/norbekov-mark.svg",
        "dark": "/static/main/brand/norbekov-mark.svg",
    },
    "DASHBOARD_CALLBACK": "main.views.dashboard_callback",
    # DIQQAT: unfold 0.67 bu qiymatlarni to'g'ridan-to'g'ri `var(--color-primary-600)`
    # ichiga qo'yadi va CSS rangi sifatida ishlatadi. Shuning uchun ular haqiqiy CSS
    # rangi bo'lishi shart — "82 82 82" ko'rinishidagi RGB triplet brauzer tomonidan
    # e'tiborsiz qoldiriladi va butun interfeys kulrangga aylanib qoladi.
    "COLORS": {
        # Dorixona/tibbiyotga mos to'q ko'k-yashil (teal) palitra. 600 qiymati
        # oq matn bilan WCAG AA dan o'tadigan darajada to'q tanlangan.
        "primary": {
            "50": "#eefcfd",
            "100": "#d5f7f9",
            "200": "#afeff3",
            "300": "#7be2e8",
            "400": "#3bc9d4",
            "500": "#19aebb",
            "600": "#0b8695",
            "700": "#086a79",
            "800": "#075361",
            "900": "#073f4b",
            "950": "#00213d",
        },
        # Neytral kulrang ohangga bir oz iliqlik/ko'klik qo'shiladi — sof qora-oq
        # o'rniga yumshoqroq fon beradi.
        "base": {
            "50": "#f7fafc",
            "100": "#edf3f7",
            "200": "#dce7ee",
            "300": "#bfd0dc",
            "400": "#8ba5b7",
            "500": "#657f92",
            "600": "#4c6374",
            "700": "#3d505f",
            "800": "#263b4c",
            "900": "#122b40",
            "950": "#00213d",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Ish stoli",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": "/admin/",
                        "permission": "main.permissions.can_access_dashboard",
                    },
                    {
                        "title": "Maosh hisob-kitobi",
                        "icon": "payments",
                        "link": "/salaries/",
                        "permission": "main.permissions.can_access_salaries",
                    },
                    {
                        "title": "QR skaner",
                        "icon": "qr_code_scanner",
                        "link": "/qr-verify/",
                        "permission": "main.permissions.can_access_qr",
                    },
                ],
            },
            {
                "title": "Ma'lumotlar",
                "separator": True,
                "items": [
                    {
                        "title": "Kurslar",
                        "icon": "school",
                        "link": "/admin/main/course/",
                        "permission": "main.permissions.can_view_courses",
                    },
                    {
                        "title": "Guruhlar",
                        "icon": "groups",
                        "link": "/admin/main/group/",
                        "permission": "main.permissions.can_view_groups",
                    },
                    {
                        "title": "Mijozlar",
                        "icon": "people",
                        "link": "/admin/main/client/",
                        "permission": "main.permissions.can_view_clients",
                    },
                    {
                        "title": "Telegram foydalanuvchilar",
                        "icon": "send",
                        "link": "/admin/main/telegramuser/",
                        "permission": "main.permissions.can_manage_users",
                    },
                    {
                        "title": "Reklama va xabarlar",
                        "icon": "campaign",
                        "link": "/admin/main/telegramcampaign/",
                        "permission": "main.permissions.can_manage_users",
                    },
                    {
                        "title": "Mini App xaridlari",
                        "icon": "shopping_bag",
                        "link": "/admin/main/miniapppurchase/",
                        "permission": "main.permissions.can_manage_users",
                    },
                    {
                        "title": "Yuridik roziliklar",
                        "icon": "verified_user",
                        "link": "/admin/main/legalacceptance/",
                        "permission": "main.permissions.can_manage_users",
                    },
                    {
                        "title": "Foydalanuvchilar",
                        "icon": "manage_accounts",
                        "link": "/admin/main/operator/",
                        "permission": "main.permissions.can_manage_users",
                    },
                    {
                        "title": "Rollar va ruxsatlar",
                        "icon": "shield_person",
                        "link": "/admin/main/roleconfiguration/",
                        "permission": "main.permissions.can_manage_users",
                    },
                    {
                        "title": "Chegirmalar",
                        "icon": "sell",
                        "link": "/admin/main/discount/",
                        "permission": "main.permissions.can_view_discounts",
                    },
                ],
            },
            {
                "title": "Moliya",
                "separator": True,
                "items": [
                    {
                        "title": "To'lovlar",
                        "icon": "payments",
                        "link": "/admin/main/transaction/",
                        "active": _is_payments_view,
                        "permission": "main.permissions.can_view_transactions",
                    },
                    {
                        "title": "Tasdiqlash navbati",
                        "icon": "pending_actions",
                        "link": "/admin/main/transaction/?is_confirmed__exact=0",
                        "active": _is_unconfirmed_transactions_view,
                        "permission": "main.permissions.can_view_transactions",
                    },
                    {
                        "title": "Ichki to'lovlar",
                        "icon": "receipt_long",
                        "link": "/admin/main/subtransaction/?status__exact=pending",
                        "permission": "main.permissions.can_view_subtransactions",
                    },
                    {
                        "title": "Qaytarilganlar",
                        "icon": "assignment_return",
                        "link": "/admin/main/transaction/?is_refunded__exact=1",
                        "active": _is_refunded_transactions_view,
                        "permission": "main.permissions.can_view_transactions",
                    },
                    {
                        "title": "Kirim-chiqim va balans",
                        "icon": "account_balance_wallet",
                        "link": "/cashflow/",
                        "permission": "main.permissions.can_access_cashflow",
                    },
                    {
                        "title": "Xarajatlar",
                        "icon": "receipt_long",
                        "link": "/admin/main/expense/",
                        "permission": "main.permissions.can_view_expenses",
                    },
                ],
            },
        ],
    },
}
