# Generated by Django 4.2.30 on 2026-07-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_refunded',
            field=models.BooleanField(default=False, verbose_name='Qaytarilgan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refunded_at',
            field=models.DateField(blank=True, null=True, verbose_name='Qaytarilgan sana'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('crm_existing', "Avvaldan CRM da bo'lgan"), ('website', 'Saytdan tushgan'), ('phone_self', "O'zi telefon qilgan"), ('manual', "Sotuvchi qo'lda kiritgan"), ('bot', 'Bot amoCRM ga kiritgan')], default='manual', max_length=20, verbose_name='Sotuv manbasi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_detail',
            field=models.CharField(blank=True, help_text="Masalan, sayt nomi (saytdan tushgan bo'lsa).", max_length=255, null=True, verbose_name='Manba tafsiloti'),
        ),
    ]
