# Generated by Django 4.2.30 on 2026-07-08 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_transaction_is_refunded_transaction_refunded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Chegirma miqdori')),
                ('is_booking', models.BooleanField(default=False, help_text="Belgilansa, bron to'lovlarida avtomatik qo'llanadi.", verbose_name='Bron chegirmasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ('-is_booking', 'name'),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='amocrm_id',
            field=models.BigIntegerField(blank=True, help_text='amoCRM dagi kontakt ID raqami.', null=True, unique=True, verbose_name='amoCRM ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='amoCRM sinxron sanasi'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Faol bo'lmagan guruhlar yangi to'lovlarda ko'rsatilmaydi.", verbose_name='Faol'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqladi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Jami chegirma'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='screenshot',
            field=models.ImageField(blank=True, help_text="To'lov chekining rasmi yoki skrinshoti.", null=True, upload_to='payment_screenshots/%Y/%m/', verbose_name='Chek / skrinshot'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('amocrm_website', "amoCRM'da bor — sayt orqali"), ('amocrm_other', "amoCRM'da bor — boshqa"), ('not_in_amocrm', "amoCRM'da yo'q")], default='not_in_amocrm', max_length=20, verbose_name='Sotuv manbasi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_detail',
            field=models.CharField(blank=True, help_text="Masalan, sayt nomi (sayt orqali kelgan bo'lsa).", max_length=255, null=True, verbose_name='Manba tafsiloti'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_booking': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.discount', verbose_name="Qo'shimcha chegirma"),
        ),
    ]
