# Generated by Django 4.2.30 on 2026-07-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_discount_client_amocrm_id_client_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='Mijozni yaratgan operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.operator', verbose_name='Operator'),
        ),
    ]
