# Generated by Django 4.2.30 on 2026-07-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_teacher_remove_group_name_group_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='price',
        ),
    ]
