# Generated by Django 4.2.30 on 2026-07-22 23:06

import uuid

from django.db import migrations, models


def gen_uuids(apps, schema_editor):
    """Mavjud mijozlarga yagona UUID beradi (har bir qator uchun alohida)."""
    Client = apps.get_model('main', 'Client')
    for client in Client.objects.all():
        client.uuid = uuid.uuid4()
        client.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_group_price'),
    ]

    operations = [
        # 1-bosqich: maydonni unique bo'lmagan holda qo'shamiz.
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Mijozning yagona identifikatori (QR kod uchun ishlatiladi).', verbose_name='UUID'),
        ),
        # 2-bosqich: mavjud qatorlarni yagona qiymatlar bilan to'ldiramiz.
        migrations.RunPython(gen_uuids, migrations.RunPython.noop),
        # 3-bosqich: endi maydonni unique qilamiz.
        migrations.AlterField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Mijozning yagona identifikatori (QR kod uchun ishlatiladi).', unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='group',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text="To'lov tasdiqlanganda QR kod yuboriladigan Telegram guruhning chat ID si (masalan -1001234567890).", max_length=64, null=True, verbose_name='Telegram guruh ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('bron', 'Bron'), ('doplata', 'Doplata'), ('to_liq_tolov', "To'liq to'lov"), ('naqd', 'Naqd pul')], max_length=20, verbose_name="To'lov turi"),
        ),
    ]
