# Generated by Django 4.2.30 on 2026-07-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_client_uuid_group_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='amocrm_lead_id',
            field=models.BigIntegerField(blank=True, help_text='Mijozga mos keluvchi amoCRM lead (bitim) ID raqami.', null=True, verbose_name='amoCRM Lead ID'),
        ),
    ]
