# Generated by Django 4.2.30 on 2026-07-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_client_amocrm_lead_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy summa')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.operator', verbose_name='Operator')),
            ],
            options={
                'verbose_name': "To'lov to'plami (oilaviy)",
                'verbose_name_plural': "To'lov to'plamlari (oilaviy)",
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='batch',
            field=models.ForeignKey(blank=True, help_text="Bir nechta mijoz uchun bitta to'lovda kiritilgan bo'lsa, ular shu to'plamga biriktiriladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.paymentbatch', verbose_name="Oilaviy to'lov to'plami"),
        ),
    ]
