# Generated by Django 4.2.30 on 2026-07-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_paymentbatch_transaction_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='telegram_chat_id',
        ),
    ]
