# Generated by Django 4.2.30 on 2026-07-29 13:53 (hand-split from autodetector output)

from django.db import migrations, models
import django.db.models.deletion


def backfill_transaction_clients(apps, schema_editor):
    Transaction = apps.get_model('main', 'Transaction')
    TransactionClient = apps.get_model('main', 'TransactionClient')
    for tx in Transaction.objects.all():
        TransactionClient.objects.create(
            transaction_id=tx.pk,
            client_id=tx.client_id,
            share_amount=tx.amount,
            share_discount=tx.discount_total,
            debt=tx.debt,
        )


def unbackfill_transaction_clients(apps, schema_editor):
    apps.get_model('main', 'TransactionClient').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_group_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Ulush miqdori')),
                ('share_discount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Ulush chegirmasi')),
                ('debt', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Qarzi')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='main.client', verbose_name='Mijoz')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.transaction', verbose_name="To'lov")),
            ],
            options={
                'verbose_name': "To'lov ishtirokchisi",
                'verbose_name_plural': "To'lov ishtirokchilari",
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='clients',
            field=models.ManyToManyField(related_name='transactions', through='main.TransactionClient', to='main.client', verbose_name='Mijozlar'),
        ),
        migrations.AddConstraint(
            model_name='transactionclient',
            constraint=models.UniqueConstraint(fields=('transaction', 'client'), name='uniq_transaction_client'),
        ),
        migrations.RunPython(backfill_transaction_clients, unbackfill_transaction_clients),
    ]
