# Generated by Django 4.2.30 on 2026-07-29 13:53 (hand-split from autodetector output)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_transactionclient_transaction_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debt',
        ),
        migrations.DeleteModel(
            name='PaymentBatch',
        ),
    ]
