# Generated by Django 4.2.30 on 2026-08-01 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_remove_transaction_client_debt_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov miqdori")),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Qabul qilingan vaqt')),
                ('clients', models.ManyToManyField(related_name='sub_transactions', to='main.client', verbose_name='Mijozlar')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_sub_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qildi')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_transactions', to='main.transaction', verbose_name="Asosiy to'lov")),
            ],
            options={
                'verbose_name': "Ichki to'lov",
                'verbose_name_plural': "Ichki to'lovlar",
                'ordering': ('-received_at', '-id'),
                'constraints': [models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='subtransaction_amount_gt_zero')],
            },
        ),
    ]
