# Generated by Django 4.2.30 on 2026-08-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_subtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtransaction',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='subtransaction_receipts/%Y/%m/', verbose_name='Chek / skrinshot'),
        ),
    ]
