# Generated by Django 4.2.30 on 2026-08-03 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_subtransaction_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtransaction',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd pul'), ('karta', 'Plastik karta'), ('bank', "Bank o'tkazmasi"), ('online', 'Online (Payme / Click)')], default='naqd', help_text='Naqd pulda chek talab qilinmaydi, qolgan turlarda majburiy.', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='subtransaction',
            name='review_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='subtransaction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt"),
        ),
        migrations.AddField(
            model_name='subtransaction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sub_transactions', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqdi"),
        ),
        migrations.AddField(
            model_name='subtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Tasdiq kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=10, verbose_name='Holati'),
        ),
    ]
