# Generated by Django 4.2.30 on 2026-08-20 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_operator_view_subtransaction_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operator',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='operator',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator / sotuvchi'), ('owner', 'Biznes egasi / tadbirkor'), ('accountant', 'Buxgalter / kassir')], default='operator', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='RoleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator / sotuvchi'), ('owner', 'Biznes egasi / tadbirkor'), ('accountant', 'Buxgalter / kassir')], max_length=20, unique=True, verbose_name='Rol')),
                ('permissions', models.ManyToManyField(blank=True, help_text="Ushbu rol foydalana oladigan bo'lim va amallarni belgilang.", to='auth.permission', verbose_name="Ochiq bo'lim va funksiyalar")),
            ],
            options={
                'verbose_name': 'Rol ruxsatlari',
                'verbose_name_plural': 'Rollar va ruxsatlar',
                'ordering': ('code',),
                'permissions': (('access_dashboard', "Dashboardni ko'rish"), ('access_salary_report', "Maosh hisobotini ko'rish"), ('access_qr_scanner', 'QR skanerdan foydalanish'), ('access_cashflow', "Kirim-chiqim va kassa balansini ko'rish")),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('category', models.CharField(choices=[('rent', 'Ijara'), ('salary', 'Maosh'), ('marketing', 'Marketing'), ('supplies', "Xo'jalik xarajatlari"), ('tax', 'Soliq'), ('utilities', 'Kommunal xizmatlar'), ('other', 'Boshqa')], max_length=20, verbose_name='Kategoriya')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqt')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ('-date', '-id'),
            },
        ),
    ]
