# Generated by Django 4.2.30 on 2026-08-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_seed_roles_and_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Kursda qatnashyapti'), ('partial', 'Qisman qatnashdi'), ('first_day_only', 'Birinchi kun keldi, keyin kelmadi'), ('never_attended', 'Umuman kelmadi'), ('completed', 'Kursni yakunladi')], default='active', max_length=20, verbose_name='Davomat holati')),
                ('last_attended_at', models.DateField(blank=True, editable=False, null=True, verbose_name='Oxirgi kelgan sana')),
                ('absence_reason', models.TextField(blank=True, help_text="Mijoz aytgan sabab yoki bog'lanish natijasini yozing.", verbose_name='Kelmaslik sababi')),
                ('operator_note', models.TextField(blank=True, help_text="Keyingi bog'lanish uchun muhim tafsilotlar.", verbose_name='Operator izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='main.client', verbose_name='Mijoz')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Kartani yaratdi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='main.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Davomat kartasi',
                'verbose_name_plural': 'Davomat / kelmagan mijozlar',
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AttendanceLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Dars sanasi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name="Dars bo'yicha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Belgilangan vaqt')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.attendancerecord', verbose_name='Davomat kartasi')),
                ('marked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Belgiladi')),
            ],
            options={
                'verbose_name': 'Qatnashgan dars',
                'verbose_name_plural': 'Qatnashgan darslar',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('client', 'group'), name='uniq_attendance_client_group'),
        ),
        migrations.AddConstraint(
            model_name='attendancelesson',
            constraint=models.UniqueConstraint(fields=('attendance', 'date'), name='uniq_attendance_lesson_date'),
        ),
    ]
