# Generated by Django 4.2.30 on 2026-09-01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_group_duration_daily_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purchase_type', models.CharField(choices=[('self', "O'zim uchun"), ('family', 'Oila uchun')], default='self', max_length=10, verbose_name='Xarid turi')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bir kishi uchun narx')),
                ('participant_count', models.PositiveSmallIntegerField(default=1, verbose_name='Ishtirokchilar soni')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Jami summa')),
                ('payment_status', models.CharField(choices=[('pending', "To\'lov kutilmoqda"), ('success', "To\'langan"), ('failed', "To\'lov amalga oshmadi")], default='pending', max_length=10, verbose_name="To'lov holati")),
                ('payment_provider', models.CharField(blank=True, default='demo', max_length=30, verbose_name="To'lov provayderi")),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name="To'lov identifikatori")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt")),
                ('questionnaire_completed', models.BooleanField(default=False, verbose_name='Anketa yakunlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mini_app_purchases', to='main.course', verbose_name='Kurs')),
            ],
            options={'verbose_name': 'Mini App xaridi', 'verbose_name_plural': 'Mini App xaridlari', 'ordering': ('-created_at', '-id')},
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('onboarding_step', models.CharField(choices=[('name', 'Ism kutilmoqda'), ('contact', 'Kontakt kutilmoqda'), ('ready', 'Tayyor')], default='name', max_length=12, verbose_name='Onboarding bosqichi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_accounts', to='main.client', verbose_name='CRM mijoz')),
            ],
            options={'verbose_name': 'Telegram foydalanuvchi', 'verbose_name_plural': 'Telegram foydalanuvchilar', 'ordering': ('-updated_at', '-id')},
        ),
        migrations.CreateModel(
            name='MiniAppPurchaseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('relationship', models.CharField(choices=[('self', 'Xaridor'), ('family', "Oila a'zosi")], default='family', max_length=10, verbose_name='Ishtirokchi turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_enrollments', to='main.client', verbose_name='CRM mijoz')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.miniapppurchase', verbose_name='Xarid')),
            ],
            options={'verbose_name': 'Xarid ishtirokchisi', 'verbose_name_plural': 'Xarid ishtirokchilari', 'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='miniapppurchase', name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='main.telegramuser', verbose_name='Telegram foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='EnrollmentQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('city', models.CharField(max_length=120, verbose_name='Shahar / tuman')),
                ('occupation', models.CharField(blank=True, max_length=160, verbose_name='Kasb / faoliyat')),
                ('learning_goal', models.TextField(verbose_name='Kursdan maqsad')),
                ('prior_experience', models.TextField(blank=True, verbose_name='Oldingi tajriba')),
                ('health_notes', models.TextField(blank=True, verbose_name="Muhim sog'liq izohlari")),
                ('consent', models.BooleanField(default=False, verbose_name="Ma'lumotlar to'g'riligini tasdiqladi")),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yakunlangan vaqt')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='main.miniapppurchasemember', verbose_name='Ishtirokchi')),
            ],
            options={'verbose_name': 'Kurs anketasi', 'verbose_name_plural': 'Kurs anketalari', 'ordering': ('-completed_at', '-id')},
        ),
        migrations.AddConstraint(
            model_name='miniapppurchasemember',
            constraint=models.UniqueConstraint(fields=('purchase', 'phone_number'), name='uniq_purchase_member_phone'),
        ),
    ]
