# Generated by Django 4.2.30 on 2026-09-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_mini_app_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Faqat CRM ichida ko'rinadigan nom.", max_length=160, verbose_name='Kampaniya nomi')),
                ('message', models.TextField(help_text='Telegram HTML formatidan foydalanish mumkin.', max_length=4096, verbose_name='Xabar matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='telegram_campaigns/%Y/%m/', verbose_name='Reklama rasmi')),
                ('button_text', models.CharField(blank=True, max_length=64, verbose_name='Tugma matni')),
                ('button_url', models.URLField(blank=True, verbose_name='Tugma havolasi')),
                ('button_opens_mini_app', models.BooleanField(default=False, help_text='Belgilanganda Telegram foydalanuvchini tasdiqlangan Mini App oynasida ochadi.', verbose_name="Tugma Mini App'ni ochadi")),
                ('audience', models.CharField(choices=[('ready', 'Onboardingni yakunlaganlar'), ('all', 'Barcha Telegram foydalanuvchilar')], default='ready', max_length=12, verbose_name='Qabul qiluvchilar')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('queued', 'Navbatda'), ('sending', 'Yuborilmoqda'), ('completed', 'Yakunlandi'), ('completed_errors', 'Xatolar bilan yakunlandi')], default='draft', editable=False, max_length=24, verbose_name='Holati')),
                ('total_recipients', models.PositiveIntegerField(default=0, editable=False, verbose_name='Jami')),
                ('queued_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Navbatda')),
                ('sent_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Yuborildi')),
                ('failed_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Xato')),
                ('blocked_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Bot bloklangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('queued_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Navbatga qo'yilgan vaqt")),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Boshlangan vaqt')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Yakunlangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='telegram_campaigns_created', to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('queued_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_campaigns_queued', to=settings.AUTH_USER_MODEL, verbose_name="Navbatga qo'ydi")),
            ],
            options={
                'verbose_name': 'Telegram xabari',
                'verbose_name_plural': 'Telegram reklama va xabarlar',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TelegramCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Navbatda'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato'), ('blocked', 'Bot bloklangan')], default='queued', max_length=12, verbose_name='Holati')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar')),
                ('error_message', models.CharField(blank=True, max_length=500, verbose_name='Xato tafsiloti')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi urinish')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='main.telegramcampaign', verbose_name='Kampaniya')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_deliveries', to='main.telegramuser', verbose_name='Telegram foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Telegram xabar qabul qiluvchisi',
                'verbose_name_plural': 'Telegram xabar qabul qiluvchilar',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='telegramcampaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'telegram_user'), name='uniq_campaign_telegram_user'),
        ),
    ]
