# Generated by Django 4.2.30 on 2026-09-05 07:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_legal_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniapppurchase',
            name='payment_provider',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name="To'lov provayderi"),
        ),
        migrations.AlterField(
            model_name='miniapppurchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('success', "To'langan"), ('failed', "To'lov amalga oshmadi"), ('refunded', "To'lov qaytarilgan")], default='pending', max_length=10, verbose_name="To'lov holati"),
        ),
        migrations.CreateModel(
            name='MulticardInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('payment_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('store_id', models.CharField(max_length=100)),
                ('amount', models.PositiveBigIntegerField(help_text='UZS tiyin')),
                ('checkout_url', models.URLField(blank=True, max_length=2000)),
                ('receipt_url', models.URLField(blank=True, max_length=2000)),
                ('state', models.CharField(choices=[('creating', 'Creating'), ('ready', 'Ready'), ('uncertain', 'Needs reconciliation'), ('success', 'Paid'), ('error', 'Failed'), ('revert', 'Refunded')], default='creating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='multicard_invoice', to='main.miniapppurchase')),
            ],
        ),
    ]
