# Generated by Django 4.2.30 on 2026-09-09 05:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_miniapppurchase_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='course',
            field=models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa barcha kurslarga amal qiladi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='main.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='discount',
            name='min_participants',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Masalan, 2: bir xaridda kamida 2 kishi bo'lsa, har biriga chegirma. Bo'sh bo'lsa qo'lda tanlanadi.", null=True, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Avtomatik chegirma uchun eng kam ishtirokchilar soni'),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='discount_name',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name="Qo'llangan chegirma"),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='discount_per_person',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Bir kishi uchun chegirma'),
        ),
    ]
