# Generated by Django 4.2.30 on 2026-09-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_course_discount_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='discount',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_booking': False, 'min_participants__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.discount', verbose_name="Qo'shimcha chegirma"),
        ),
    ]
