# Generated by Django 4.2.30 on 2026-09-16 12:48

from django.db import migrations, models
import django.db.models.deletion


def preserve_paid_purchases(apps, schema_editor):
    Purchase = apps.get_model('main', 'MiniAppPurchase')
    Purchase.objects.using(schema_editor.connection.alias).filter(payment_status='success').update(
        paid_amount=models.F('total_amount'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_automatic_discount_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniapppurchase',
            name='booking_discount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Bron chegirmasi (kelishilgan)'),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name="Qo'llangan chegirma"),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='is_booking',
            field=models.BooleanField(default=False, verbose_name="Bron orqali to'lash"),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='miniapppurchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('partial', "Bron qilingan — qisman to'langan"), ('success', "To'langan"), ('failed', "To'lov amalga oshmadi"), ('refunded', "To'lov qaytarilgan")], default='pending', max_length=10, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='multicardinvoice',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multicard_invoices', to='main.miniapppurchase'),
        ),
        migrations.AddConstraint(
            model_name='multicardinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('creating', 'ready', 'uncertain', 'error'))), fields=('purchase',), name='one_open_multicard_invoice'),
        ),
        migrations.RunPython(preserve_paid_purchases, migrations.RunPython.noop),
    ]
