# Generated by Django 4.2.30 on 2026-09-17 04:50

import django.core.validators
from django.db import migrations, models


def seed_settings(apps, schema_editor):
    apps.get_model('main', 'PaymentSettings').objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_mini_app_booking_installments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('minimum_booking_amount', models.PositiveIntegerField(default=100000, help_text="Test uchun 1000, odatiy bron uchun 100000 kiriting. Yangi to'lovlarga darhol amal qiladi; ochilgan to'lov hisoblari o'zgarmaydi.", validators=[django.core.validators.MinValueValidator(1)], verbose_name="Bir kishi uchun eng kam bron to'lovi (so'm)")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': "To'lov sozlamalari",
                'verbose_name_plural': "To'lov sozlamalari",
            },
        ),
        migrations.AddConstraint(
            model_name='paymentsettings',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='payment_settings_singleton'),
        ),
        migrations.AddConstraint(
            model_name='paymentsettings',
            constraint=models.CheckConstraint(check=models.Q(('minimum_booking_amount__gte', 1)), name='positive_booking_minimum'),
        ),
        migrations.RunPython(seed_settings, migrations.RunPython.noop),
    ]
