# Generated by Django 4.2.30 on 2026-09-20 00:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def populate_referrals_and_payment_dates(apps, schema_editor):
    Operator = apps.get_model('main', 'Operator')
    for operator in Operator.objects.using(schema_editor.connection.alias).all():
        operator.referral_code = uuid.uuid4()
        operator.save(update_fields=['referral_code'], using=schema_editor.connection.alias)
    Invoice = apps.get_model('main', 'MulticardInvoice')
    Invoice.objects.using(schema_editor.connection.alias).filter(state='success').update(paid_at=models.F('updated_at'))
    # The old payment_type described purpose, not method. Do not guess historical methods.
    apps.get_model('main', 'Transaction').objects.using(schema_editor.connection.alias).exclude(payment_type='naqd').update(payment_method='')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_payment_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner',
            field=models.ImageField(blank=True, upload_to='group_banners/%Y/%m/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='referrer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_purchases', to='main.operator'),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='social_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Ijtimoiy chegirma'),
        ),
        migrations.AddField(
            model_name='multicardinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='referral_code',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referrer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_accounts', to='main.operator'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('terminal', 'Terminal'), ('rahmat', 'Rahmat')], default='naqd', max_length=20, verbose_name='To‘lov usuli'),
        ),
        migrations.AlterField(
            model_name='subtransaction',
            name='payment_method',
            field=models.CharField(choices=[('naqd', 'Naqd'), ('terminal', 'Terminal'), ('rahmat', 'Rahmat'), ('karta', 'Plastik karta'), ('bank', "Bank o'tkazmasi"), ('online', 'Online (Payme / Click)')], default='naqd', help_text='Naqd pulda chek talab qilinmaydi, qolgan turlarda majburiy.', max_length=20, verbose_name="To'lov turi"),
        ),
        migrations.CreateModel(
            name='PaymentQRDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.multicardinvoice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.miniapppurchasemember')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('pensioner', 'Pensioner'), ('disability', 'Nogironligi bor'), ('student', 'Talaba')], max_length=20)),
                ('storage_name', models.CharField(editable=False, max_length=200)),
                ('original_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.telegramuser')),
            ],
        ),
        migrations.AddField(
            model_name='miniapppurchasemember',
            name='eligibility_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='main.eligibilitydocument'),
        ),
        migrations.RunPython(populate_referrals_and_payment_dates, migrations.RunPython.noop),
        migrations.AlterField(model_name='operator', name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
        migrations.AddConstraint(
            model_name='paymentqrdelivery',
            constraint=models.UniqueConstraint(fields=('invoice', 'member'), name='unique_payment_member_qr'),
        ),
    ]
