# Generated by Django 4.2.30 on 2026-09-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_customer_payment_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('self', "O'zim uchun"), ('family', 'Oila uchun')], default='self', max_length=10, verbose_name='Xarid turi')),
                ('payment_mode', models.CharField(choices=[('booking', "Bron — bo'lib to'lash"), ('full', "To'liq to'lov")], default='booking', max_length=10, verbose_name="To'lov tartibi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Savatga qo'shilgan vaqt")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='main.course', verbose_name='Kurs')),
                ('eligibility_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.eligibilitydocument', verbose_name='Xaridor chegirma hujjati')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='main.group', verbose_name='Tanlangan guruh')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='main.telegramuser', verbose_name='Telegram foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Savatdagi kurs',
                'verbose_name_plural': 'Web app savati',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='checkout_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='Savat partiyasi'),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='group',
            field=models.ForeignKey(blank=True, help_text="To'lovlar shu guruhning to'lovlar ro'yxatiga yoziladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_app_purchases', to='main.group', verbose_name='Guruh'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mini_app_purchase',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_payment', to='main.miniapppurchase', verbose_name='Web app xaridi'),
        ),
        migrations.AlterField(
            model_name='miniapppurchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('partial', "Bron qilingan — qisman to'langan"), ('success', "To'langan"), ('failed', "To'lov amalga oshmadi"), ('refunded', "To'lov qaytarilgan"), ('cancelled', 'Savatga qaytarilgan')], default='pending', max_length=10, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('amocrm_website', "amoCRM'da bor — sayt orqali"), ('amocrm_other', "amoCRM'da bor — boshqa"), ('not_in_amocrm', "amoCRM'da yo'q"), ('telegram_app', 'Telegram web app')], default='not_in_amocrm', max_length=20, verbose_name='Sotuv manbasi'),
        ),
        migrations.CreateModel(
            name='MiniAppCartMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('eligibility_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.eligibilitydocument', verbose_name='Chegirma hujjati')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.miniappcartitem', verbose_name='Savatdagi kurs')),
            ],
            options={
                'verbose_name': "Savatdagi oila a'zosi",
                'verbose_name_plural': "Savatdagi oila a'zolari",
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='miniappcartitem',
            constraint=models.UniqueConstraint(fields=('telegram_user', 'course'), name='uniq_cart_course_per_user'),
        ),
    ]
