# Generated by Django 4.2.30 on 2026-09-28 12:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_web_app_cart_group_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='channel_removal_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Guruh boshlanganidan necha kun o'tgach to'lovni to'liq qilmaganlar kanaldan chiqariladi. Bo'sh qoldirilsa, hech kim chiqarilmaydi.", null=True, validators=[django.core.validators.MaxValueValidator(365)], verbose_name="To'liq to'lov muddati (kun)"),
        ),
        migrations.AddField(
            model_name='group',
            name='telegram_channel_id',
            field=models.CharField(blank=True, help_text="Masalan -1001234567890 yoki @kanal_nomi. Bot kanalda admin bo'lishi shart.", max_length=64, verbose_name='Telegram kanal ID'),
        ),
        migrations.AddField(
            model_name='group',
            name='telegram_channel_title',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Telegram kanal nomi'),
        ),
        migrations.CreateModel(
            name='TelegramChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Havola tayyorlanmoqda'), ('invited', 'Havola berilgan'), ('joined', 'Kanalda'), ('removed', 'Chiqarilgan')], default='new', max_length=12, verbose_name='Holat')),
                ('invite_link', models.CharField(blank=True, max_length=255, verbose_name='Shaxsiy havola')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Kanalga kirgan Telegram ID')),
                ('link_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Havola yuborilgan vaqt')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Kanalga kirgan vaqt')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Chiqarilgan vaqt')),
                ('next_sync_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Keyingi tekshiruv')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Oxirgi xato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to='main.client', verbose_name='Mijoz')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_members', to='main.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': "Kanal a'zosi",
                'verbose_name_plural': "Kanal a'zolari",
            },
        ),
        migrations.AddConstraint(
            model_name='telegramchannelmember',
            constraint=models.UniqueConstraint(fields=('group', 'client'), name='uniq_channel_member_group_client'),
        ),
    ]
