# Generated by Django 4.2.30 on 2026-10-06 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0032_telegram_channel_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniapppurchase',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_links', to=settings.AUTH_USER_MODEL, verbose_name='Havolani yaratdi'),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='crm_transaction',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='main.transaction', verbose_name="Qarzi to'lanadigan CRM to'lovi"),
        ),
        migrations.AddField(
            model_name='miniapppurchase',
            name='link_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name="To'lov havolasi kaliti"),
        ),
        migrations.AddField(
            model_name='subtransaction',
            name='multicard_invoice',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crm_installment', to='main.multicardinvoice', verbose_name="To'lov havolasi orqali to'lov"),
        ),
        migrations.AlterField(
            model_name='legalacceptance',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_acceptances', to='main.telegramuser', verbose_name='Telegram foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='miniapppurchase',
            name='payment_status',
            field=models.CharField(choices=[('pending', "To'lov kutilmoqda"), ('partial', "Bron qilingan — qisman to'langan"), ('success', "To'langan"), ('failed', "To'lov amalga oshmadi"), ('refunded', "To'lov qaytarilgan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=10, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='miniapppurchase',
            name='telegram_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='main.telegramuser', verbose_name='Telegram foydalanuvchi'),
        ),
    ]
